### ISSUE TITLE
Craft warning: Element query executed before Craft is fully initialized

### ISSUE THREAD

**Issue by daltonrooney** [spicywebau/craft-content-templates#3]
### Bug Description

This is very minor, but thought it might be helpful for you to know. When Content Templates is the only enabled plugin, I see a notice in my logs when creating a new entry:

```
08-23 16:57:58 [web.WARNING] [craft\elements\db\ElementQuery::prepare] Element query executed before Craft is fully initialized.
```

```
Stack trace:
#0 /var/www/html/craft/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
#1 /var/www/html/craft/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
#2 /var/www/html/craft/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand()
#3 /var/www/html/craft/vendor/craftcms/cms/src/db/Query.php(275): yii\db\Query->one()
#4 /var/www/html/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1595): craft\db\Query->one()
#5 /var/www/html/craft/vendor/craftcms/cms/src/elements/User.php(525): craft\elements\db\ElementQuery->one()
#6 /var/www/html/craft/vendor/yiisoft/yii2/web/User.php(698): craft\elements\User::findIdentity()
#7 /var/www/html/craft/vendor/craftcms/cms/src/web/User.php(500): yii\web\User->renewAuthStatus()
#8 /var/www/html/craft/vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#9 /var/www/html/craft/vendor/craftcms/cms/src/web/User.php(257): yii\web\User->getIdentity()
#10 /var/www/html/craft/vendor/spicyweb/craft-content-templates/src/Plugin.php(77): craft\web\User->getIsAdmin()
#11 /var/www/html/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): spicyweb\contenttemplates\Plugin->init()
#12 /var/www/html/craft/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct()
#13 /var/www/html/craft/vendor/craftcms/cms/src/base/Plugin.php(122): yii\base\Module->__construct()
#14 craft\base\Plugin->__construct()
#15 /var/www/html/craft/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#16 /var/www/html/craft/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#17 /var/www/html/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#18 /var/www/html/craft/vendor/craftcms/cms/src/Craft.php(54): yii\BaseYii::createObject()
#19 /var/www/html/craft/vendor/craftcms/cms/src/services/Plugins.php(943): Craft::createObject()
#20 /var/www/html/craft/vendor/craftcms/cms/src/services/Plugins.php(228): craft\services\Plugins->createPlugin()
#21 /var/www/html/craft/vendor/craftcms/cms/src/base/ApplicationTrait.php(1582): craft\services\Plugins->loadPlugins()
#22 /var/www/html/craft/vendor/craftcms/cms/src/web/Application.php(108): craft\web\Application->_postInit()
#23 /var/www/html/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#24 /var/www/html/craft/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#25 yii\base\Application->__construct()
#26 /var/www/html/craft/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#27 /var/www/html/craft/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#28 /var/www/html/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#29 /var/www/html/craft/vendor/craftcms/cms/src/Craft.php(54): yii\BaseYii::createObject()
#30 /var/www/html/craft/vendor/craftcms/cms/bootstrap/bootstrap.php(256): Craft::createObject()
#31 /var/www/html/craft/vendor/craftcms/cms/bootstrap/web.php(40): require()
#32 /var/www/html/public/index.php(25): require() {"memory":2439224} 
```

It goes away when the plugin is disabled. 

My guess it's related to this line: https://github.com/spicywebau/craft-content-templates/blob/ad30326ea584cb03b7de8c76fa87a4e544b5b569/src/Plugin.php#L77

That check should be delayed until after the Craft application init event, see https://github.com/craftcms/cms/issues/11033#issuecomment-1111754160

### Steps to reproduce

* Enable plugin
* Create a new Entry

### Content Templates version

1.0.2

### Craft CMS version

4.1.17

**Comment by ttempleton** [comment]
Thanks for pointing that out - fixed for the next release.
